function [point_x_0_right,point_y_0_right,point_x_0_left,point_y_0_left]=PoolCenters(numberOfHalfEyes)
[point_x_0_right_circleOne,point_y_0_right_circleOne]=CalculateCenterOfCirclesInRightEyeCircleOne(numberOfHalfEyes);
[point_x_0_right_circleTwo,point_y_0_right_circleTwo]=CalculateCenterOfCirclesInRightEyeCircleTwo(numberOfHalfEyes);
[point_x_0_right_circleThree,point_y_0_right_circleThree]=CalculateCenterOfCirclesInRightEyeCircleThree(numberOfHalfEyes);

[point_x_0_left_circleOne,point_y_0_left_circleOne]=CalculateCenterOfCirclesInLeftEyeCircleOne(numberOfHalfEyes);
[point_x_0_left_circleTwo,point_y_0_left_circleTwo]=CalculateCenterOfCirclesInLeftEyeCircleTwo(numberOfHalfEyes);
[point_x_0_left_circleThree,point_y_0_left_circleThree]=CalculateCenterOfCirclesInLeftEyeCircleThree(numberOfHalfEyes);

point_x_0_right=[point_x_0_right_circleOne,point_x_0_right_circleTwo,point_x_0_right_circleThree];
point_y_0_right=[point_y_0_right_circleOne,point_y_0_right_circleTwo,point_y_0_right_circleThree];
point_x_0_left=[point_x_0_left_circleOne,point_x_0_left_circleTwo,point_x_0_left_circleThree];
point_y_0_left=[point_y_0_left_circleOne,point_y_0_left_circleTwo,point_y_0_left_circleThree];